CREATE TABLE "algoshpe_admin" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "algoshpe_admin_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(100) NOT NULL,
	"email" varchar(100) NOT NULL,
	"password" varchar(100) NOT NULL,
	"auth_id" uuid NOT NULL,
	CONSTRAINT "algoshpe_admin_username_unique" UNIQUE("username"),
	CONSTRAINT "algoshpe_admin_email_unique" UNIQUE("email"),
	CONSTRAINT "algoshpe_admin_auth_id_unique" UNIQUE("auth_id")
);
--> statement-breakpoint
CREATE TABLE "algoshpe_assignment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "algoshpe_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(100) NOT NULL,
	"description" text,
	"due_date" date,
	"submission_ids" integer[],
	"starter_code" text,
	"test_cases" text,
	"hints" text
);
--> statement-breakpoint
CREATE TABLE "algoshpe_comment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "algoshpe_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer,
	"admin_id" integer,
	"parent_id" integer,
	"is_private" boolean,
	"message" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "algoshpe_material" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "algoshpe_material_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(100) NOT NULL,
	"file_url" varchar(255),
	"uploaded" timestamp
);
--> statement-breakpoint
CREATE TABLE "algoshpe_student" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "algoshpe_student_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ucf_id" integer NOT NULL,
	"first_name" varchar(100),
	"last_name" varchar(100),
	"username" varchar(100) NOT NULL,
	"email" varchar(100) NOT NULL,
	"password" varchar(100) NOT NULL,
	"attendance" integer,
	"algoshpe_points" integer DEFAULT 0,
	"currentAssignments" integer[],
	"pastAssignments" integer[],
	CONSTRAINT "algoshpe_student_ucf_id_unique" UNIQUE("ucf_id"),
	CONSTRAINT "algoshpe_student_username_unique" UNIQUE("username"),
	CONSTRAINT "algoshpe_student_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "algoshpe_submission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "algoshpe_submission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer,
	"assignment_id" integer NOT NULL,
	"code" text NOT NULL,
	"output" text NOT NULL,
	"status" text NOT NULL,
	"submitted_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "algoshpe_comment" ADD CONSTRAINT "algoshpe_comment_student_id_algoshpe_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."algoshpe_student"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "algoshpe_comment" ADD CONSTRAINT "algoshpe_comment_admin_id_algoshpe_admin_id_fk" FOREIGN KEY ("admin_id") REFERENCES "public"."algoshpe_admin"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "algoshpe_submission" ADD CONSTRAINT "algoshpe_submission_student_id_algoshpe_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."algoshpe_student"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "algoshpe_submission" ADD CONSTRAINT "algoshpe_submission_assignment_id_algoshpe_assignment_id_fk" FOREIGN KEY ("assignment_id") REFERENCES "public"."algoshpe_assignment"("id") ON DELETE no action ON UPDATE no action;